CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230404105325_Initial') THEN
    CREATE TABLE "Chat" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Model" text NOT NULL,
        "CurrentUsage" integer NOT NULL,
        "TotalUsage" integer NOT NULL,
        "LastSendTime" timestamp with time zone NULL,
        "Audit" jsonb NOT NULL,
        CONSTRAINT "PK_Chat" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230404105325_Initial') THEN
    CREATE TABLE "Message" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ChatId" bigint NOT NULL,
        "Order" bigint NOT NULL,
        "Type" integer NOT NULL,
        "Content" text NOT NULL,
        "Usage" integer NOT NULL,
        "Audit" jsonb NOT NULL,
        CONSTRAINT "PK_Message" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Message_Chat_ChatId" FOREIGN KEY ("ChatId") REFERENCES "Chat" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230404105325_Initial') THEN
    CREATE TABLE "ChatOperatorLog" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Operator" integer NOT NULL,
        "ChatId" bigint NOT NULL,
        "MessageId" bigint NOT NULL,
        "ReceivedId" bigint NOT NULL,
        "PromptUsage" integer NOT NULL,
        "CompletionUsage" integer NOT NULL,
        "Audit" jsonb NOT NULL,
        CONSTRAINT "PK_ChatOperatorLog" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ChatOperatorLog_Chat_ChatId" FOREIGN KEY ("ChatId") REFERENCES "Chat" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_ChatOperatorLog_Message_MessageId" FOREIGN KEY ("MessageId") REFERENCES "Message" ("Id"),
        CONSTRAINT "FK_ChatOperatorLog_Message_ReceivedId" FOREIGN KEY ("ReceivedId") REFERENCES "Message" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230404105325_Initial') THEN
    CREATE INDEX "IX_ChatOperatorLog_ChatId" ON "ChatOperatorLog" ("ChatId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230404105325_Initial') THEN
    CREATE INDEX "IX_ChatOperatorLog_MessageId" ON "ChatOperatorLog" ("MessageId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230404105325_Initial') THEN
    CREATE INDEX "IX_ChatOperatorLog_ReceivedId" ON "ChatOperatorLog" ("ReceivedId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230404105325_Initial') THEN
    CREATE INDEX "IX_Message_ChatId" ON "Message" ("ChatId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230404105325_Initial') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20230404105325_Initial', '7.0.4');
    END IF;
END $EF$;
COMMIT;

