// <auto-generated />
using System;
using Althea.Data;
using Althea.Infrastructure.EntityFrameworkCore.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Althea.Data.Migrations
{
    [DbContext(typeof(AltheaDbContext))]
    partial class AltheaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Althea.Data.Domains.ChatDomain.Chat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DeletableAudit>("Audit")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("CurrentUsage")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastSendTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Own")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer");

                    b.Property<int>("TotalUsage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Chat", (string)null);
                });

            modelBuilder.Entity("Althea.Data.Domains.ChatDomain.ChatOperatorLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<BasicAudit>("Audit")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<int>("CompletionUsage")
                        .HasColumnType("integer");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<int>("Operator")
                        .HasColumnType("integer");

                    b.Property<int>("PromptUsage")
                        .HasColumnType("integer");

                    b.Property<long>("ReceivedId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("MessageId");

                    b.HasIndex("ReceivedId");

                    b.ToTable("ChatOperatorLog", (string)null);
                });

            modelBuilder.Entity("Althea.Data.Domains.ChatDomain.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DeletableAudit>("Audit")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Order")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("Usage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("Althea.Data.Domains.ChatDomain.ChatOperatorLog", b =>
                {
                    b.HasOne("Althea.Data.Domains.ChatDomain.Chat", "Chat")
                        .WithMany("Logs")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Althea.Data.Domains.ChatDomain.Message", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId");

                    b.HasOne("Althea.Data.Domains.ChatDomain.Message", "Received")
                        .WithMany()
                        .HasForeignKey("ReceivedId");

                    b.Navigation("Chat");

                    b.Navigation("Message");

                    b.Navigation("Received");
                });

            modelBuilder.Entity("Althea.Data.Domains.ChatDomain.Message", b =>
                {
                    b.HasOne("Althea.Data.Domains.ChatDomain.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("Althea.Data.Domains.ChatDomain.Chat", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
